// fetch('https://jsonplaceholder.typicode.com/posts?_limit=15').then(res => res.json()).then(posts => (this.posts = posts))

export default [
  {
    "Heading": "Got Plans for Spring Break?",
    "SubHeading": "5 ways to stay busy when Hillsborough County's public schools take a breather in mid-March",
    "Body": "<p>Looking for something to do during spring break?<\/p>\r\n<p>The annual leave of absence is March 18-22 for students at Hillsborough County public schools.<\/p>\r\n<p>The County offers plenty of fun, wholesome activities for students of all ages. <\/p>\r\n<p>Here are a few:<\/p>\r\n<p>At <a href=\"\/en\/residents\/recreation-and-culture\/kids\/camp-days\">Spring Break Camp,<\/a> children in kindergarten through eighth grade spend time with their friends, and meet new ones, in a supervised, fun-filled atmosphere. And it's not too soon to consider registering children and teens for <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/residents\/recreation-and-culture\/kids\/action-folder\/register-for-summer-camp\">Summer Camp.<\/a> Programs are available for kids with varied interests and abilities, and <a href=\"\/en\/newsroom\/2019\/03\/07\/you-may-qualify-for-summer-camp-discounts\">you might qualify for financial assistance<\/a>.<\/p>\r\n<p>Off-the-beaten path <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/newsroom\/2018\/06\/20\/beat-the-heat-at-these-distinctive-museums\">museums and attractions<\/a> are a fun and interesting way to spend a day, or more. <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/newsroom\/2018\/06\/08\/discovery-pass\">Discovery Pass,<\/a> available to anyone with a Hillsborough County Public Library Cooperative card, provides discounts to some of these, and other, museums and attractions.<\/p>\r\n<p>Get outdoors. Plan a <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/newsroom\/2017\/05\/26\/roll-out-to-a-hillsborough-county-bicycle-trail\">bicycle ride, <\/a> an excursion to a <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/newsroom\/2017\/03\/03\/u-pick\">U-Pick field,<\/a> an <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/newsroom\/2017\/08\/23\/hillsborough-has-gone-to-the-dogs\">outing with your dog,<\/a> or a <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/residents\/recreation-and-culture\/outdoor-recreation\/camping\">camping trip.<\/a> The annual <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/calendar\/03-parksandrec\/2019\/20190316-great-american-campout\">Great American Campout,<\/a> for kids and families, is March 16 and 17, the first weekend of spring break.<\/p>\r\n<p>Line up a <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/newsroom\/2019\/02\/12\/summer-job-opportunities-with-hillsborough-county\">summer job.<\/a> Hillsborough County is hiring teens for part-time and seasonal jobs including lifeguard, recreation leader, and intern in various departments.<\/p>\r\n<p><a href=\"https:\/\/www.hillsboroughcounty.org\/en\/residents\/citizens\/volunteers\">Volunteer<\/a> during spring break, or throughout the year. Teens are especially helpful with Children's Services and Head Start programs.<\/p>",
    "Excerpt": "Looking for something to do during spring break? The annual leave of absence is March 18-22 for...",
    "Image": { "Src": "https://www.hillsboroughcounty.org/library/hillsborough/jumping-kids_nr.jpg" },
    "DestinationUrl": "#1",
    "Icon": "fas fa-newspaper",
    "PublishDate": new Date("2019-03-09"),
    "Category": "News",
    "Tags": ['a tag', 'word', 'another tag'],
    "Keywords": []
  },
  {
    "Heading": "Scam Likely",
    "SubHeading": "7 things to know for 2019 Consumer Protection Week",
    "Body": "<p>Looking to protect yourself from fraud, identity theft, and scams? Maybe you're wondering about the best way to use credit, how to recover stolen wages, or maximize your security online. Hillsborough County Consumer &amp; Veterans Services has tips and resources to inform and empower consumers during National Consumer Protection Week, March 3-9, that will last throughout the year.<\/p>\r\n<h3>Know your trespass towing rights<\/h3>\r\n<p>\r\nDid you know Hillsborough County has <a href=\"\/en\/residents\/citizens\/consumer-issues\/towing-companies\">standards of service and requirements<\/a> in place for towing and wrecker companies to protect residents and visitors from deceptive business practices? As part of these requirements, all companies conducting trespass towing in Hillsborough County from private property must:<\/p>\r\n<ul>\r\n    <li>Alert law enforcement within 30 minutes of the vehicle removal explaining the tow<\/li>\r\n    <li>Accept consumers' money orders, cashier's checks, debit cards, and cash to pay the bill<\/li>\r\n    <li>Provide a legible, written receipt bearing the name of the towing company, the list of charges imposed, and payments received <\/li>\r\n<\/ul>\r\n<p>Consumers with trespass towing-related concerns can <a href=\"\/en\/residents\/citizens\/consumer-issues\/action-folder\/report-a-complaint-against-a-business\">file a complaint electronically<\/a> or in person at one of the four <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/residents\/citizens\/consumer-issues\/consumer-protection-offices\">Hillsborough County Consumer Protection Offices<\/a>. <\/p>\r\n<h3>Protect yourself from the \"Grandparent Scam\"<\/h3>\r\n<p>\r\nSeniors nationwide are receiving calls from scammers claiming to be their grandchild. A typical scenario is this: The \"grandson\" claims to have been in a car accident and it's his fault. He needs money in the form of a gift card, so he won't go to jail. The scammers then instruct their elderly victim to call a cab, go to a store, purchase gift cards, and call back with the gift card pin numbers.<\/p>\r\n<p>In an effort to help individuals before they become victims, law enforcement agencies around the country are asking people who work in an environment that sells gift cards to ask questions when an elderly person needs thousands of dollars in these cards. Victims can <a rel=\"noopener noreferrer\" href=\"https:\/\/www.ftccomplaintassistant.gov\" target=\"_blank\">report fraud to the Federal Trade Commission online<\/a>, or by calling their Consumer Response Center at (877) 382-4357. You may also call Hillsborough County Consumer &amp; Veterans Services at (813) 635-8316.<\/p>\r\n<h3>Be aware of \"phishy\" email<\/h3>\r\n<p>\r\n<a href=\"https:\/\/www.consumer.ftc.gov\/articles\/0003-phishing\">Phishing<\/a> is when someone uses a familiar company name or pretends to be someone you know to send you fake emails or text messages, hoping to get you to share valuable personal information such as account numbers, Social Security numbers, or your login IDs and passwords. Scammers are after your identity and money. Some phishing emails are trying to gain access to your computer or network. For example, you may click on a link, and scammers can then install ransomware or other programs that can lock you out of your data. Take <a rel=\"noopener noreferrer\" href=\"https:\/\/www.consumer.ftc.gov\/articles\/0003-phishing\" target=\"_blank\">these steps<\/a> before clicking on an email link or sharing any sensitive information, and <a rel=\"noopener noreferrer\" href=\"https:\/\/www.ftc.gov\/complaint\" target=\"_blank\">report phishing to the Federal Trade Commission<\/a>. <\/p>\r\n<h3>Use credit and debit cards wisely<\/h3>\r\n<p>\r\nPeople often use debit cards to control their spending. But did you know there is less protection if you are a victim of debit card fraud than if you had used your credit card and it was compromised?These tips will help you determine when it's best to use your debit or credit card:<\/p>\r\n<ul>\r\n    <li>Don't use your debit card for online purchases. Paying by credit card is safer and comes with more protection.<\/li>\r\n    <li>Don't use your debit card at a gas station. Gas stations are prime targets and statistics show that 1.3 percent of payment fraud in the U.S. occurs at fuel pumps.<\/li>\r\n    <li>It's better to use cash or credit when eating out.<\/li>\r\n    <li>Book your hotel with a credit card because hotels might put a hold on your debit payment, sometimes for $100 or more.<\/li>\r\n    <li>Rent a car using your credit card to avoid a hold on your debit card and a credit check.<\/li>\r\n    <li>Big ticket items should be paid with a credit card. If unsatisfied, you can dispute the charges.<\/li>\r\n    <li>Free-standing ATM's put your debit card in danger because the machines are less likely to be monitored. Use the ATM at a physical bank.<\/li>\r\n<\/ul>\r\n<h3>Don't fall victim to wage theft<\/h3>\r\n<p>\r\nWorking off the clock, stealing tips, not paying overtime, requiring unpaid training, and mis-classifying workers are just a few ways dishonest employers might steal wages. Wage theft often affects low-income workers in construction, agriculture, and service industries. The burden of proof rests upon the employee who needs evidence to support their claim and win their case. <a href=\"https:\/\/www.hillsboroughcounty.org\/en\/residents\/citizens\/consumer-issues\/wage-recovery\">Learn more<\/a> about this national problem and Hillsborough County's local solution.<\/p>\r\n<h3>Funeral Fraud and scams can cost you in your time of grief<\/h3>\r\n<p>\r\nEach year, people spend billions of dollars arranging funerals for family members and friends. <a rel=\"noopener noreferrer\" href=\"https:\/\/www.consumer.ftc.gov\/articles\/0070-shopping-funeral-services\" target=\"_blank\">These funeral planning tips<\/a> will help make expensive funeral services more affordable.<\/p>\r\n<p>The federal government protects consumers from unfair business practices with a law called <a rel=\"noopener noreferrer\" href=\"https:\/\/www.consumer.ftc.gov\/articles\/0300-ftc-funeral-rule\" target=\"_blank\">The Funeral Rule<\/a>. For assistance, consumers can <a rel=\"noopener noreferrer\" href=\"https:\/\/www.ftccomplaintassistant.gov\" target=\"_blank\">contact the Federal Trade Commission<\/a>, the agency that enforces this rule and offers guidelines for consumers planning a funeral. <\/p>\r\n<h3>Understanding Buyer's Remorse and \"The Cooling-off Rule\"<\/h3>\r\n<ul>\r\n    <li>\r\n    There is no automatic three day right to rescind \"all sales\" in Florida.<\/li>\r\n    <li>In Florida, if you contract for services to be rendered in the future on a continuing basis, you are entitled to a three-day cooling-off period under state law.<\/li>\r\n    <li>You are also entitled to cancel a contract for future services if you can no longer physically receive the services, or the services are no longer available as originally offered.<\/li>\r\n    <li>If you purchase goods or services worth more than $25, during the course of a \"home solicitation sale,\" you maintain a three-day right to cancel. A sale is considered a \"home solicitation sale\" if it takes place in your home, or at a location which is not the main or permanent place of business for the seller. <\/li>\r\n<\/ul>\r\n<p>There are some exclusions and limitations under the <a rel=\"noopener noreferrer\" href=\"https:\/\/www.consumer.ftc.gov\/articles\/0176-buyers-remorse-when-ftcs-cooling-rule-may-help\" target=\"_blank\">law<\/a>. If you have questions, contact Hillsborough County Consumer Protection Services Division at (813) 635-8316. <\/p>\r\n<p><a href=\"https:\/\/www.hillsboroughcounty.org\/government\/departments\/consumer\">Visit Consumer Protection<\/a><a href=\"https:\/\/www.hillsboroughcounty.org\/government\/departments\/consumer\"> online<\/a>, file a consumer complaint, search existing consumer complaints, or learn more about the County's Consumer Protection education programs.<\/p>",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "https://www.hillsboroughcounty.org/library/hillsborough/creditcard_nr.png" },
    "DestinationUrl": "#1",
    "Icon": "fas fa-money-check-alt",
    "PublishDate": new Date("2019-03-18"),
    "Category": "Consumer Protection",
    "Tags": ['a tag', 'word', 'another tag'],
    "Keywords": []
  },
  {
    "Heading": "Qui Est Esse",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/controlled-burn_nr.jpg" },
    "DestinationUrl": "#2",
    "Icon": "fas fa-fire",
    "PublishDate": "",
    "Category": "Prescribed Burn",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Ea Molestias Quasi Exercitationem Repellat Qui Ipsa Sit Aut",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "https://www.hillsboroughcounty.org/library/hillsborough/smallkitten_nr.png" },
    "DestinationUrl": "#3",
    "Icon": "fas fa-paw",
    "PublishDate": "",
    "Category": "Pets",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Eum Et Est Occaecati",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/hc_completed-mural-tampa-bay-history-center_nr2.jpg" },
    "DestinationUrl": "#4",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Sunt Aut Facere Repellat Provident Occaecati Excepturi Optio Reprehenderit",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "https://www.hillsboroughcounty.org/library/hillsborough/campday3.jpg" },
    "DestinationUrl": "#1",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Qui Est Esse",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/controlled-burn_nr.jpg" },
    "DestinationUrl": "#2",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Ea Molestias Quasi Exercitationem Repellat Qui Ipsa Sit Aut",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/street-hockey_nr.jpg" },
    "DestinationUrl": "#3",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Eum Et Est Occaecati",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/hc_completed-mural-tampa-bay-history-center_nr2.jpg" },
    "DestinationUrl": "#4",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Sunt Aut Facere Repellat Provident Occaecati Excepturi Optio Reprehenderit",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/super-flush_hero3.jpg" },
    "DestinationUrl": "#1",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Qui Est Esse",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/controlled-burn_nr.jpg" },
    "DestinationUrl": "#2",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Ea Molestias Quasi Exercitationem Repellat Qui Ipsa Sit Aut",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/street-hockey_nr.jpg" },
    "DestinationUrl": "#3",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
  {
    "Heading": "Eum Et Est Occaecati",
    "SubHeading": "",
    "Body": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Excerpt": "quia et suscipit suscipit recusandae consequuntur expedita et cum reprehenderit molestiae ut ut quas totam nostrum rerum est autem sunt rem eveniet architecto",
    "Image": { "Src": "http://hcflgov.net/library/hillsborough/hc_completed-mural-tampa-bay-history-center_nr2.jpg" },
    "DestinationUrl": "#4",
    "Icon": "fas fa-newspaper",
    "PublishDate": "",
    "Category": "News",
    "Tags": [],
    "Keywords": []
  },
]
